apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simon-frontend
      component: simon-frontend
  template:
    metadata:
      labels:
        app: simon-frontend
        component: simon-frontend
    spec:
      containers:
        - name: simon-frontend
          image: ghcr.io/Rafaelnacho1/frontend:latest   
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simon-frontend
spec:
  type: ClusterIP
  selector:
    app: simon-frontend
    component: simon-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simon-frontend
spec:
  to:
    kind: Service
    name: simon-frontend
  port:
    targetPort: 8080
