apiVersion: v1
kind: Secret
metadata:
  name: simon-db-password
type: Opaque
data:
  username: Z3Vlc3Rib29r
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: simon-redis-password
type: Opaque
data:
  password: cGFzc3dvcmQ=
